// chat action creator constants
export const FETCH_CHATS = 'FETCH_CHATS';
export const FETCH_CHATS_LOADING = 'FETCH_CHATS_LOADING';
export const FETCH_CHATS_SUCCESS = 'FETCH_CHATS_SUCCESS';
export const FETCH_CHATS_FAILURE = 'FETCH_CHATS_FAILURE';

export const ADD_CHAT_MESSAGE = 'ADD_CHAT_MESSAGE';
export const ADD_CHAT_MESSAGE_LOADING = 'ADD_CHAT_MESSAGE_LOADING';
export const ADD_CHAT_MESSAGE_SUCCESS = 'ADD_CHAT_MESSAGE_SUCCESS';
export const ADD_CHAT_MESSAGE_FAILURE = 'ADD_CHAT_MESSAGE_FAILURE';

export const ADD_BOT_CHAT_REPLY = 'ADD_BOT_CHAT_REPLY';
export const ADD_BOT_CHAT_REPLY_LOADING = 'ADD_BOT_CHAT_REPLY_LOADING';
export const ADD_BOT_CHAT_REPLY_SUCCESS = 'ADD_BOT_CHAT_REPLY_SUCCESS';
export const ADD_BOT_CHAT_REPLY_FAILURE = 'ADD_BOT_CHAT_REPLY_FAILURE';
